services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    image: project
    environment:
      - DATABASE_URL=postgresql+psycopg://user:password@db/db
      - APP_ENV=development
    stdin_open: true
    tty: true
    ports:
      - 8100:8080
    volumes:
      - '../src:/app/src'
      - '../requirements:/app/requirements'
      - '../scripts:/app/scripts'
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    ports:
      - 5555:5432
    command: --fsync=off
    networks:
      default:
        aliases:
          - db

volumes:
  pgdata:
